import fs from "fs";
import path from "path";
import { parseEnvFiles, EnvSpec, KeyInfo } from "../parser/index.js";
import { logger } from "../utils/logger.js";
import { detectPlatform, platformLabel } from "../utils/platform.js";

export async function generateTypesFromEnv(opts?: {
  cwd?: string;
  outDir?: string;
  profile?: string;
  strict?: boolean;
}) {
  const cwd = opts?.cwd || process.cwd();
  let outDir = opts?.outDir;
  if (!outDir) {
    const srcPath = path.join(cwd, "src");
    if (fs.existsSync(srcPath) && fs.statSync(srcPath).isDirectory()) {
      outDir = srcPath;
    } else {
      outDir = cwd;
    }
  }

  const platform = detectPlatform();
  if (platform !== "local") {
    logger.info(`Detected ${platformLabel(platform)} — reading vars from process.env where no .env file is present.`);
  }

  const spec = await parseEnvFiles({ cwd, profile: opts?.profile, strict: opts?.strict });

  const dts = buildDts(spec);
  const ts = buildRuntimeTs(spec);

  const dtsPath = path.join(outDir, "env.auto.d.ts");
  const tsPath = path.join(outDir, "env.auto.ts");

  await fs.promises.writeFile(dtsPath, dts, "utf8");
  await fs.promises.writeFile(tsPath, ts, "utf8");

  logger.success(`Wrote types to ${dtsPath}`);
  logger.success(`Wrote runtime stub to ${tsPath}`);

  return { dtsPath, tsPath, spec };
}

function tsTypeFor(v: KeyInfo): string {
  switch (v.type) {
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "enum":
      return (v.enumValues || []).map((e) => `"${e}"`).join(" | ") || "string";
    case "url":
    case "string":
    default:
      return "string";
  }
}

function buildDts(spec: EnvSpec): string {
  const lines: string[] = [];
  lines.push("declare module 'env-auto' {");
  lines.push("  export interface EnvType {");
  for (const [k, v] of Object.entries(spec.keys)) {
    const t = tsTypeFor(v);
    const optional = v.required ? "" : "?";
    lines.push(`    ${k}${optional}: ${t};`);
  }
  lines.push("  }");
  lines.push("  export const nomad: EnvType;");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function parseExprFor(k: string, v: KeyInfo): string {
  switch (v.type) {
    case "number":
      return `Number(process.env['${k}'])`;
    case "boolean":
      return `(String(process.env['${k}']).toLowerCase() === 'true')`;
    default:
      return `process.env['${k}']`;
  }
}

function buildRuntimeTs(spec: EnvSpec): string {
  const lines: string[] = [];
  lines.push("/**");
  lines.push(" * This file is auto-generated by env-auto. It provides a runtime typed wrapper for process.env.");
  lines.push(" * Do not edit - changes will be overwritten.");
  lines.push(" */");
  lines.push('/// <reference types="node" />');
  lines.push("");
  lines.push("export const nomad = {");
  for (const [k, v] of Object.entries(spec.keys)) {
    const parseExpr = parseExprFor(k, v);
    lines.push(`  ${k}: ${parseExpr} as any,`);
  }
  lines.push("} as const;\n");
  return lines.join("\n");
}