import fs from "fs";
import path from "path";
import { parseEnvFiles, EnvSpec } from "../parser/index.js";
export type { EnvSpec };
import { logger } from "../utils/logger.js";

export async function generateTypesFromEnv(opts?: { cwd?: string; outDir?: string }) {
  const cwd = opts?.cwd || process.cwd();
  
  let outDir = opts?.outDir;
  if (!outDir) {
    const srcPath = path.join(cwd, "src");
    if (fs.existsSync(srcPath) && fs.statSync(srcPath).isDirectory()) {
      outDir = srcPath;
    } else {
      outDir = cwd;
    }
  }

  const spec: EnvSpec = await parseEnvFiles({ cwd });

  const dts = buildDts(spec);
  const ts = buildRuntimeTs(spec);

  const dtsPath = path.join(outDir, "env.auto.d.ts");
  const tsPath = path.join(outDir, "env.auto.ts");

  await fs.promises.writeFile(dtsPath, dts, "utf8");
  await fs.promises.writeFile(tsPath, ts, "utf8");

  logger.success(`Wrote types to ${dtsPath}`);
  logger.success(`Wrote runtime stub to ${tsPath}`);
  return { dtsPath, tsPath };
}

function buildDts(spec: EnvSpec) {
  const lines: string[] = [];
  lines.push("declare module 'env-auto' {");
  lines.push("  export interface EnvType {");
  for (const [k, v] of Object.entries(spec.keys)) {
    const t = v.type === "number" ? "number" : v.type === "boolean" ? "boolean" : "string";
    lines.push(`    ${k}: ${t};`);
  }
  lines.push("  }");
  lines.push("  export const nomad: EnvType;");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function buildRuntimeTs(spec: EnvSpec) {
  const lines: string[] = [];
  lines.push("/**");
  lines.push(" * This file is auto-generated by env-auto. It provides a runtime typed wrapper for process.env.");
  lines.push(" * Do not edit - changes will be overwritten.");
  lines.push(" */");
  lines.push("/// <reference types=\"node\" />");
  lines.push("");
  lines.push("export const nomad = {");
  for (const [k, v] of Object.entries(spec.keys)) {
    const parseExpr = v.type === "number" ? `Number(process.env['${k}'])` : v.type === "boolean" ? `(String(process.env['${k}']).toLowerCase() === 'true')` : `process.env['${k}']`;
    lines.push(`  ${k}: ${parseExpr} as any,`);
  }
  lines.push("} as const;\n");
  return lines.join("\n");
}
// Note: EnvSpec type is defined in parser and exported there.
